#!/usr/bin/env python3
"""
gen_tones.py
============
Generates tones.h for the Arduino Nano R4 xylophone synthesizer.

Precomputes damped-sine coefficients for two octaves of chromatic pitches
(C4–B5, 24 notes) using the second-order IIR recurrence:

    x[n] = coeff * x[n-1] - rho2 * x[n-2]

where coeff = 2·ρ·cos(ω), rho2 = ρ², and ρ = exp(−1 / (τ · fs)).

Each note has NUM_PARTIALS partials; per-partial parameters come from
the InstrumentDef below. Decay time τ is register-scaled by tau_scale
per octave relative to A4 = 440 Hz (lower notes decay slower).

The seed stored per partial is rel_amp · (−sin(ω) / ρ), normalised so
that multiplying by the strike amplitude at trigger time initialises
x[n-2] correctly with no further trig.

Usage:
    python gen_tones.py > tones.h
"""

import math
import sys
from dataclasses import dataclass, field
from typing import List

# ── Synthesis parameters ───────────────────────────────────────────────────────

SAMPLE_RATE = 22050          # Hz — must match Arduino sketch
REF_FREQ    = 440.0          # A4, reference for tau_scale
NUM_PARTIALS = 3

# ── Instrument definition ──────────────────────────────────────────────────────

@dataclass
class PartialDef:
    """
    One partial of a struck-bar idiophone.

    freq_ratio : partial frequency as a multiple of the note's fundamental
    tau_mid    : decay time constant (seconds) at REF_FREQ (A4 = 440 Hz)
    tau_scale  : decay-time multiplier per octave *below* REF_FREQ
                 (> 1 → longer decay in the bass, matching real bars)
    amp_ratio  : partial amplitude as a fraction of the note amplitude
    """
    freq_ratio : float
    tau_mid    : float
    tau_scale  : float
    amp_ratio  : float

@dataclass
class InstrumentDef:
    name     : str
    partials : List[PartialDef]

XYLOPHONE = InstrumentDef(
    name="xylophone",
    partials=[
        PartialDef(freq_ratio=1.0, tau_mid=0.30, tau_scale=1.5, amp_ratio=1.00),
        PartialDef(freq_ratio=3.0, tau_mid=0.08, tau_scale=1.3, amp_ratio=0.45),
        # PartialDef(freq_ratio=6.0, tau_mid=0.03, tau_scale=1.1, amp_ratio=0.18),
        PartialDef(freq_ratio=6.0, tau_mid=0.03, tau_scale=1.1, amp_ratio=0.5),
    ],
)

# ── Note table: C4 – B5 (24 chromatic pitches) ────────────────────────────────

# Note names for enum identifiers (S = sharp)
_NAMES = ['C', 'CS', 'D', 'DS', 'E', 'F', 'FS', 'G', 'GS', 'A', 'AS', 'B']

def midi_to_freq(midi: int) -> float:
    return 440.0 * 2.0 ** ((midi - 69) / 12.0)

def build_note_list():
    """Return list of (enum_name, display_name, freq_hz) for C4–B5."""
    notes = []
    for octave in (4, 5):
        for semitone, name in enumerate(_NAMES):
            midi      = (octave + 1) * 12 + semitone
            freq      = midi_to_freq(midi)
            enum_name = f"NOTE_{name}{octave}"
            display   = name.replace('S', '#')
            notes.append((enum_name, f"{display}{octave}", freq))
    return notes

NOTES = build_note_list()

# ── Coefficient computation ────────────────────────────────────────────────────

def octaves_from_ref(freq: float) -> float:
    """Signed octaves above A4; negative = below."""
    return math.log2(freq / REF_FREQ)

def partial_coeffs(fund_freq: float, pdef: PartialDef, fs: int):
    """
    Return (coeff, rho2, seed) for one partial.

    seed = amp_ratio · (−sin(ω) / ρ)   [unit-amplitude seed, includes rel_amp]

    At trigger: x[n-2] = strike_amplitude · seed
                x[n-1] = 0
    The inner loop then emits x[n-1] before advancing state, so the first
    non-zero sample appears at n=1 as expected for a sine starting from zero.
    """
    oct_below = -octaves_from_ref(fund_freq)   # positive in bass
    tau   = pdef.tau_mid * (pdef.tau_scale ** oct_below)
    rho   = math.exp(-1.0 / (tau * fs))
    omega = 2.0 * math.pi * (fund_freq * pdef.freq_ratio) / fs

    coeff = 2.0 * rho * math.cos(omega)
    rho2  = rho * rho
    seed  = pdef.amp_ratio * (-math.sin(omega) / rho)

    return coeff, rho2, seed

# ── Header generation ──────────────────────────────────────────────────────────

def generate(instrument: InstrumentDef, fs: int) -> str:
    lines = []

    lines += [
        "/* ---------------------------------------------------------------",
        " * tones.h  —  AUTO-GENERATED by gen_tones.py, do not edit.",
        f" * Instrument : {instrument.name}",
        f" * Sample rate: {fs} Hz",
        f" * Notes      : C4 – B5 (24 chromatic pitches)",
        f" * Partials   : {len(instrument.partials)} per note",
        " * --------------------------------------------------------------- */",
        "",
        "#pragma once",
        "",
        f"static const int NUM_PARTIALS = {len(instrument.partials)};",
        f"static const int NUM_NOTES    = {len(NOTES)};",
        "",
        "/* Per-partial precomputed constants (stored in flash). */",
        "struct PartialCoeff {",
        "    float coeff;   /* 2·ρ·cos(ω)                     — feedback coefficient */",
        "    float rho2;    /* ρ²                              — damping coefficient  */",
        "    float seed;    /* rel_amp·(−sin(ω)/ρ)            — scaled initial cond. */",
        "};",
        "",
        "/* All partials for one note. */",
        "struct NoteCoeff {",
        "    PartialCoeff partials[NUM_PARTIALS];",
        "};",
        "",
        "/* Symbolic note identifiers — use in SENSOR_NOTE[] in the sketch. */",
        "enum NoteID {",
    ]

    for enum_name, _, _ in NOTES:
        lines.append(f"    {enum_name},")
    lines += ["    NUM_NOTE_IDS", "};", ""]

    lines.append("static const NoteCoeff NOTE_TABLE[NUM_NOTES] = {")

    for enum_name, display, freq in NOTES:
        lines.append(f"    /* {enum_name}  ({display} = {freq:.2f} Hz) */")
        lines.append(    "    { {")
        for pdef in instrument.partials:
            coeff, rho2, seed = partial_coeffs(freq, pdef, fs)
            pfreq = freq * pdef.freq_ratio
            lines.append(
                f"        {{ {coeff:>15.10f}f, {rho2:>15.10f}f, {seed:>15.10f}f }},"
                f"  /* ×{pdef.freq_ratio:.0f} = {pfreq:7.1f} Hz */"
            )
        lines.append("    } },")

    lines += ["};", ""]
    return "\n".join(lines)

# ── Entry point ────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import sys
    sys.stdout.reconfigure(encoding='utf-8')
    print(generate(XYLOPHONE, SAMPLE_RATE))
